<a href="https://colab.research.google.com/github/fazelelham32/YouTube-Projects/blob/CNN-Projects-google-colab/NN_chapter3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**project3**

In [1]:
import numpy as np

In [2]:
inputs = np.array([0, 0])
b = np.array([-1.5, -.5])

In [3]:
weights = np.array([[1, 1] , [1, 1]])

In [4]:
and_or = np.dot(weights, inputs) + b.T
and_or

array([-1.5, -0.5])

In [5]:
if and_or[0] > 0:
    and_or[0] = 1
else:
   and_or[0] = 0

if and_or[1] > 0:
    and_or[1] = 1
else:
    and_or[1] = 0

In [6]:
and_or

array([0., 0.])

In [7]:
weights_xor = np.array([-1, 1])

In [8]:
xor = np.dot(weights_xor, and_or)
xor

np.float64(0.0)

In [9]:
if xor > 0:
    xor = 1
else:
    xor = 0

In [10]:
xor

0

In [13]:
input = np.array([1, 2, 4, 6, 32, 65])

In [14]:
weight = np.array([0.5, 0.4, 1, 0.60, 0.50, 0.6])

In [15]:
np.dot(weight, input)

np.float64(63.9)

In [16]:
weight = np.array([[0.5, 0.4, 1, 0.60, 0.50, 0.6],
                   [0.5, 0.4, 1, 0.60, 0.50, 0.6],
                   [0.5, 0.4, 1, 0.60, 0.50, 0.6]])

In [17]:
out_put1 = np.dot(weight, input)

In [18]:
weight_2 = np.array([[0.5, 0.12, 0.32],
                     [0.5, 0.12, 0.32],
                     [0.5, 0.12, 0.32]])

In [19]:
out_put2 = np.dot(weight_2, out_put1)

In [20]:
out_put2

array([60.066, 60.066, 60.066])